
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('AaS', 'Adams and Sons', 81479, '122 Schultz Spurs', 'South Dudley');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('ARC', 'Ankunding, Rutherford and Coll', 35855, '430 Bessie Landing', 'Josianeport');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('BKM','Block, Mraz and Kuphal', 15821, '636 Cayla Court Apt. 754', 'Allytown');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('BG', 'Boehm Group', 56609, '910 Prohaska Plains', 'Port Lillytown');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('BHK', 'Brown, Herzog and Kihn', 21159, '62561 Nikolaus Extension Apt. ', 'Port Vidafort');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CaMo', 'Carroll-Moore', 81665, '006 Micah Pass', 'Arvillahaven');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CaHe', 'Casper-Herman', 97258, '871 Trycia Forge', 'Lonieshire');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CGr', 'Corkery Group', 26441, '1841 Kiana Harbor Suite 863', 'North Jettland');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CrInc', 'Cronin Inc', 61337, '85588 Samantha Inlet Suite 954', 'Celineside');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CrDu', 'Cronin-Durgan', 53338, '50614 Gislason Manors Apt. 725', 'O\'Reillymouth');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('DaLtd', 'Daniel Ltd', 43539, '099 Kohler Divide', 'Alfview');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('EmInc', 'Emmerich Inc', 98553, '90954 Ruecker Walks Suite 854', 'Port Savannahhaven');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('FCM', 'Fahey, Connelly and McLaughlin', 20565, '08116 Jed Crossroad', 'North Cydneyborough');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('FaS', 'Fisher and Sons', 76821, '2680 Harmony Viaduct', 'Olsontown');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('GTM', 'Gorczany, Torp and Mraz', 76197, '53238 Collins Turnpike Suite 6', 'New Nedra');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('GrEr', 'Grady-Ernser', 24030, '845 Ansley Tunnel', 'Boscostad');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('GrInc', 'Greenholt Inc', 75910, '82351 Runolfsdottir Corners Ap', 'South Maya');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('HTP', 'Haley, Turner and Pollich', 43100, '5425 Dorcas Skyway', 'West Trinityview');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('HaHe', 'Hane-Heidenreich', 18416, '5297 Sigurd Ridge Suite 877', 'Port Calechester');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('HeRa', 'Hegmann-Rath', 62456, '851 Kessler Fork Apt. 772', 'West Robbieberg');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('HeLtd', 'Heidenreich Ltd', 41064, '812 Wolff Oval Apt. 864', 'Harberfort');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('HSJ', 'Hickle, Shanahan and Johnson', 60837, '54490 Rosenbaum Summit', 'Yadiramouth');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('JSP', 'Johnson, Shanahan and Parisian',, 51436, '8391 Dickinson Fort', 'North Lydia');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('JohnGr', 'Johnston Group', 62517, '9147 Noemi Mountains', 'Bogisichberg');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('KeInc', 'Kertzmann Inc', 49864, '23386 Gerald Knoll Suite 430', 'South Sadie');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('KHH', 'Kertzmann, Hudson and Hodkiewi', 22060, '92693 Mueller Square', 'Lake Hildegardmouth');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('KoBr', 'Kohler-Bruen', 44404, '609 Frami Port Apt. 173', 'Port Stevestad');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('KRD', 'Kohler, Ritchie and DuBuque', 68597, '4996 Ed Crescent', 'South Katheryn');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('LCK', 'Labadie, Cronin and Koch', 78102, '19799 Mckenna Rue Suite 381', 'Lemkestad');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('LeLtd', 'Leffler Ltd', 93979, '58346 Gilbert Track Suite 805', 'Dorotheaport');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('LMH', 'Littel, Mertz and Haley', 36211, '3938 Schulist Road Apt. 843', 'South Jordanburgh');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('LoSw', 'Lowe-Swaniawski', 59749, '102 Maxime Roads', 'North Soledadborough');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('MaSt', 'Marvin-Stoltenberg', 72939, '83328 Schiller Common', 'Lake Christinabury');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('MuWi', 'Murazik-Willms', 89380, '76036 Adams Plain', 'New Jonathon');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('MuLtd', 'Murray Ltd', 55741, '0518 Murphy Isle Suite 182', 'Port Candacefort');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CoGl', 'Connell-Gleason', 37447, '261 Paucek Glen Apt. 601', 'Port Gustaveside');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('CoKo', 'Collins and Kon', 24272, '61414 Sipes Inlet Suite 242', 'Vedachester');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('WJ', 'Jacobson and White', 31193, '2658 Kuhic Brook', 'Kassulkebury');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('OFad','Ortiz-Fadel', 78191, '7520 Collins Gardens Apt. 251', 'North Laverne');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('PacoG','Pacocha-Glover', 17529, '450 Wilhelmine Points Apt. 038', 'Manteland');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('StM', 'Stamm and Monahan', 75111, '4518 Johnnie Ford Apt. 650', 'Framitown');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('RuInc','Ruecker Inc', 10182, '79613 Ryan Expressway Suite 44', 'Judgechester');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('RunBa','Runolfsson-Bashirian', 17109, '47716 Hamill Shores', 'Port Bobbieton');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('RLLC','Rutherford LLC', 34309, '146 Padberg Inlet Apt. 593', 'Andersonmouth');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('RyanG','Ryan Group', 52717, '21210 Kozey Light Suite 294', 'New Alexanne');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('GK', 'Gislason and Kuvalis', 88070, '3196 Edwardo Cape', 'Lake Mariettaview');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('SteKo','Stehr-Kovacek', 39307, '86517 Turcotte Isle', 'Schummport');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('LeBa', 'Lemke and Bayer', 52663, '137 Feeney Track Apt. 128', 'Lake Alisonside');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('St.M', 'Stokes-Maggio', 72789, '640 Deckow Bypass', 'Port Maximus');
INSERT INTO `organization` (`abbreviation`, `name`, `post_code`, `road`, `town`) VALUES ('MuPu', 'Mueller and Purdy', 49742, '1074 Jamey Plains Apt. 260', 'Pagacville');
