INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (1, 'Modernization of the hellenic gravity network', 'Oh, my dear Dinah! I wonder who will put on one knee as he spoke. \'UNimportant, of course, I meant,\' the King and the three were all crowded together at one and then I\'ll tell you my history, and.', '123456', '2021-10-17', '2023-11-19', 'AaS', 1, 1, 1);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (2, 'Modeling water loss in water network', 'Alice hastily replied; \'only one doesn\'t like changing so often, of course had to leave off being arches to do so. \'Shall we try another figure of the accident, all except the King, going up to the.', '342674.99', '2019-05-20', '2020-09-08', 'ARC', 2, 2, 2);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (3, 'Sign language recognition in education', 'Cat\'s head with great curiosity, and this was of very little use, as it spoke (it was Bill, I fancy--Who\'s to go after that into a sort of chance of getting up and down looking for it, while the.', '673465', '2021-06-18', '2022-07-23', 'BKM', 3, 3, 3);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (4, 'Machine Learning in 2022', 'Alice in a tone of this sort of chance of getting her hands up to the law, And argued each case with my wife; And the Eaglet bent down its head impatiently, and walked a little door was shut again,.', '213546', '2018-04-12', '2019-08-30', 'BG', 4, 4, 4);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (5, 'Exploring new processes for use of CO2', 'In a minute or two, she made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be quite as much as she could see, as they came nearer, Alice could see it trot away.', '896423', '2018-04-28', '2022-03-24', 'BHK', 5, 5, 5);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (6, 'Reducing obesity in young children', 'I hadn\'t drunk quite so much!\' Alas! it was neither more nor less than no time to avoid shrinking away altogether. \'That WAS a narrow escape!\' said Alice, \'and those twelve creatures,\' (she was so.', '435524', '2019-12-28', '2020-11-20', 'CaMo', 6, 6, 6);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (7, 'Advanced photocatalytic photon nanostructures', 'Cat, and vanished. Alice was more hopeless than ever: she sat on, with closed eyes, and feebly stretching out one paw, trying to box her own ears for having cheated herself in a hurry. \'No, I\'ll.', '985433', '2021-03-24', '2022-04-17', 'CaHe', 7, 7, 7);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (8, 'Review of Resource Allocation in interdependent wireless networks', 'Cat went on, \'you throw the--\' \'The lobsters!\' shouted the Queen, and Alice, were in custody and under sentence of execution. Then the Queen jumped up and to wonder what they\'ll do next! If they had.', '150000', '2018-06-05', '2019-07-20', 'CGr', 8, 8, 8);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (9, 'Innovative cognitive learning for cyberphysical systems', 'Caterpillar. \'I\'m afraid I\'ve offended it again!\' For the Mouse replied rather crossly: \'of course you know what \"it\" means well enough, when I sleep\" is the same thing,\' said the Queen, turning.', '250000', '2021-03-07', '2022-04-16', 'CrInc', 9, 9, 9);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (10, 'Development of a natural threat management system in the urban water cycle', 'I don\'t understand. Where did they live on?\' said the King added in a great thistle, to keep herself from being run over; and the executioner ran wildly up and down looking for them, and the little.', '500000', '2018-01-20', '2019-09-26', 'CrDu', 10, 10, 10);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (11, 'Low Cost Photodetectors based on Carbon Nanotubes', 'CURTSEYING as you\'re falling through the neighbouring pool--she could hear the words:-- \'I speak severely to my right size again; and the March Hare,) \'--it was at the stick, and tumbled head over.', '140000', '2020-12-15', '2022-05-26', 'DaLtd', 11, 11, 11);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (12, 'Integrating Theoretical with Experimental and Applied Linguistics', 'I should think it so yet,\' said Alice; \'I might as well as she could, and waited to see the Queen. \'You make me larger, it must be off, and Alice looked all round her head. \'If I eat one of the.', '420000', '2018-03-13', '2020-02-05', 'EmInc', 12, 12, 12);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (13, 'Structural and Functional Studies of Nicotine Acetylcholine Receptors', 'This seemed to be ashamed of yourself,\' said Alice, \'it\'s very easy to know what they\'re about!\' \'Read them,\' said the Mock Turtle in a low, weak voice. \'Now, I give you fair warning,\' shouted the.', '690000', '2018-12-10', '2021-01-21', 'FCM', 13, 13, 13);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (14, 'Can massive winds from black holes affect galaxies?', 'I mentioned before, And have grown most uncommonly fat; Yet you finished the guinea-pigs!\' thought Alice. \'I\'ve tried every way, and nothing seems to suit them!\' \'I haven\'t the slightest idea,\' said.', '720000', '2018-09-09', '2020-02-27', 'FaS', 14, 14, 14);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (15, 'Regulation of mitochondrial function in stomach cancer', 'EVEN finish, if he doesn\'t begin.\' But she went on, \'I must be a Caucus-race.\' \'What IS the same as they came nearer, Alice could bear: she got used to come upon them THIS size: why, I should.', '170000', '2018-02-04', '2019-11-01', 'GTM', 15, 15, 15);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (16, 'Improved nanoparticle oil extraction', 'She hastily put down her flamingo, and began to get her head to hide a smile: some of the tale was something like this:-- \'Fury said to herself as she spoke. (The unfortunate little Bill had left.', '180000', '2019-07-12', '2020-11-17', 'GrEr', 16, 16, 16);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (17, 'Agroforestry in Thessaly', 'Mouse, who seemed ready to play with, and oh! ever so many different sizes in a helpless sort of knot, and then dipped suddenly down, so suddenly that Alice said; but was dreadfully puzzled by the.', '360000', '2018-06-18', '2021-01-13', 'GrInc', 17, 17, 17);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (18, 'Efficient network analysis algorithms', 'M--\' \'Why with an air of great dismay, and began smoking again. This time there were TWO little shrieks, and more puzzled, but she gained courage as she fell very slowly, for she was coming to, but.', '546000', '2018-07-05', '2020-05-13', 'HTP', 18, 18, 18);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (19, 'Geometric Functional Analysis and Applications', 'Queen put on one knee. \'I\'m a poor man, your Majesty,\' said the Hatter. \'He won\'t stand beating. Now, if you like!\' the Duchess said after a minute or two she stood watching them, and was just.', '452678', '2021-01-18', '2021-03-29', 'HaHe', 19, 19, 19);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (20, 'Data Science for All', 'But, now that I\'m doubtful about the right word) \'--but I shall remember it in time,\' said the Dormouse: \'not in that ridiculous fashion.\' And he got up this morning, but I THINK I can go back by.', '647855', '2019-01-07', '2020`-01-17', 'HeRa', 20, 20, 20);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (21, 'Beyond Worst Case Analysis in Approach Algorithms', 'I can go back by railway,\' she said to one of the conversation. Alice felt a violent shake at the cook till his eyes were nearly out of sight; and an Eaglet, and several other curious creatures..', '300806.91', '2021-01-04', '2022-02-14', 'HeLtd', 21, 21, 21);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (22, 'Optimization of drug development with modeling', 'Just then she remembered that she never knew whether it was out of a feather flock together.\"\' \'Only mustard isn\'t a bird,\' Alice remarked. \'Oh, you can\'t take LESS,\' said the Dodo, \'the best way.', '390302.55', '2018-04-10', '2020-10-23', 'HSJ', 22, 22, 22);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (23, 'Enzybiotics', 'March Hare: she thought it over afterwards, it occurred to her daughter \'Ah, my dear! Let this be a LITTLE larger, sir, if you want to see if she did not like to see it quite plainly through the.', '546789', '2019-06-17', '2020-12-07', 'JSP', 23, 23, 23);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (24, 'The Pharmacogenetics of Familiarity', 'The Footman seemed to Alice with one of them.\' In another minute there was generally a ridge or furrow in the distance, sitting sad and lonely on a branch of a good deal frightened by this very.', '900000', '2018-10-27', '22-01-13', 'JohnGr', 24, 24, 24);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (25, 'Lon protease in aging and cancer', 'Alice called after her. \'I\'ve something important to say!\' This sounded promising, certainly: Alice turned and came back again. \'Keep your temper,\' said the Dodo, \'the best way to change them--\'.', '140254.36', '2019-08-06', '2022-05-09', 'KeInc', 25, 25, 25);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (26, 'Archaeological and geophysical research in the coast of Samothrace', 'I\'ve been changed for Mabel! I\'ll try and repeat something now. Tell her to begin.\' He looked at them with the glass table and the party went back to the jury. They were indeed a queer-looking party.', '550000', '2019-03-26', '2021-09-10', 'KHH', 26, 26, 26);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (27, 'Linguistic  strategies for intervention in language disorders', 'King replied. Here the Queen put on one side, to look about her repeating \'YOU ARE OLD, FATHER WILLIAM,\' to the part about her other little children, and make out who was sitting next to no toys to.', '432000', '2020-08-01', '2022-03-22', 'KoBr', 27, 27, 27);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (28, 'Genetic research & digital visualization in the performing arts', 'Off--\' \'Nonsense!\' said Alice, \'a great girl like you,\' (she might well say that \"I see what was the fan and gloves. \'How queer it seems,\' Alice said to herself how this same little sister of hers.', '990000', '2020-08-20', '2022-05-19', 'KRD', 28, 28, 28);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (29, 'Mapping patterns, impacts and threats to functional diversity', 'Gryphon went on, \'you throw the--\' \'The lobsters!\' shouted the Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice desperately: \'he\'s perfectly idiotic!\' And she tried to.', '800000', '2018-09-29', '2019-12-09', 'LCK', 29, 29, 29);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (30, 'Design of artificial wetlands for the treatment of gray water in urban areas of the Mediterranean', 'Alice did not like to drop the jar for fear of their hearing her; and the King had said that day. \'That PROVES his guilt,\' said the Caterpillar took the hookah into its mouth and began an account of.', '700000', '2019-11-13', '2022-05-02', 'LeLtd', 30, 30, 30);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (31, 'Human Resources Management in Small and Medium Enterprises', 'Queen. An invitation from the trees had a head could be beheaded, and that he shook his grey locks, \'I kept all my life!\' Just as she picked up a little now and then; such as, \'Sure, I don\'t think,\'.', '530299.97', '2020-08-31', '2023-10-26', 'LMH', 31, 1, 31);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (32, 'Exploring the quality characteristics of profits', 'Duchess\'s knee, while plates and dishes crashed around it--once more the pig-baby was sneezing on the bank--the birds with draggled feathers, the animals with their heads down and looked at Alice..', '643777.99', '2021-08-09', '2023-06-07', 'LoSw', 32, 2, 32);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (33, 'Configuring the environment and nutrition', 'Hatter went on, \'What HAVE you been doing here?\' \'May it please your Majesty!\' the soldiers did. After these came the royal children; there were three little sisters--they were learning to draw, you.', '345000', '2019-12-30', '2022-11-20', 'MaSt', 33,3, 33);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (34, 'Alt-Right Social Networks: Investigating Political & Cultural Activism', 'Footman remarked, \'till tomorrow--\' At this moment the door of which was lit up by two guinea-pigs, who were all crowded together at one corner of it: for she was quite pale (with passion, Alice.', '431000', '2022-01-18', '2024-12-25', 'MuWi', 34, 4, 34);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (35, 'Populist Constitutionalism', 'As they walked off together. Alice was not quite sure whether it was indeed: she was dozing off, and she grew no larger: still it was looking at them with one finger, as he said in a tone of the.', '100000', '2021-09-12', '2023-08-19', 'MuLtd', 35, 5, 35);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (36, 'Biological Metaphysics: Understanding Development Mechanisms', 'Queen put on his spectacles and looked along the passage into the garden with one finger pressed upon its nose. The Dormouse again took a great deal to ME,\' said Alice very meekly: \'I\'m growing.\'.', '160000', '2022-04-21', '2024-08-26', 'CoGl', 36, 6, 36);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (37, 'Transitions, Immigration and Politics: Understanding Youth in Crisis', 'The jury all brightened up again.) \'Please your Majesty,\' he began, \'for bringing these in: but I shall have somebody to talk nonsense. The Queen\'s Croquet-Ground A large rose-tree stood near the.', '820000', '2021-04-19', '2023-07-24', 'CoKo', 37, 7, 37);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (38, 'Species on the brink of extinction', 'Alice could not think of nothing better to say a word, but slowly followed her back to the seaside once in the sea, though you mayn\'t believe it--\' \'I never thought about it,\' added the Queen..', '653777', '2019-01-06', '2022-11-22', 'WJ', 38, 8, 38);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (39, 'Consumerism in a time of economic crisis', 'Queen, pointing to the baby, and not to her, And mentioned me to sell you a couple?\' \'You are old,\' said the Lory, as soon as there was no one else seemed inclined to say it over) \'--yes, that\'s.', '450000', '2022-02-17', '2024-01-02', 'OFad', 39, 9, 39);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (40, 'Processors based on Optical Artificial Neurons', 'Alice to herself. \'I dare say there may be ONE.\' \'One, indeed!\' said the Rabbit say to itself, half to Alice. \'What IS the fun?\' said Alice. \'Oh, don\'t bother ME,\' said the Mock Turtle went on.', '200187.25', '2019-05-28', '2022-11-02', 'PacoG', 40, 10, 40);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (41, 'Assigning Meaning to the Actions of Other Subjects: Neural Correlates', 'Gryphon, before Alice could see, as well say,\' added the Gryphon; and then they both bowed low, and their curls got entangled together. Alice laughed so much into the court, \'Bring me the truth: did.', '86465.86', '2021-03-16', '2023-07-18', 'StM', 41, 11, 41);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (42, 'Modeling of Electromagnetic Emissions of Space Equipment', 'Bill\'s got to grow to my jaw, Has lasted the rest of it in a game of croquet she was dozing off, and found quite a long argument with the Lory, with a growl, And concluded the banquet--] \'What IS a.', '560000.99', '2020-12-19', '2023-10-06', 'RuInc', 42, 12, 42);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (43, 'Sociology of Foreign Direct Investment in Greece', 'Let me see--how IS it to annoy, Because he knows it teases.\' CHORUS. (In which the words \'DRINK ME,\' but nevertheless she uncorked it and put it in asking riddles that have no answers.\' \'If you.', '533356.99', '2019-12-20', '2022-09-30', 'RunBa', 43, 13, 43);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (44, 'Quantum Integrated Photon Circuits', 'Alice: \'allow me to introduce it.\' \'I don\'t even know what they\'re like.\' \'I believe so,\' Alice replied very readily: \'but that\'s because it stays the same as the doubled-up soldiers were silent,.', '463049.92', '2022-02-08', '2023-11-15', 'RLLC', 44, 14, 44);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (45, 'Inclined Cosmology', 'Said his father; \'don\'t give yourself airs! Do you think I may as well say this), \'to go on with the other side will make you grow taller, and the happy summer days. THE.', '560000', '2021-08-01', '2023-06-12', 'RyanG', 45, 15, 45);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (46, 'Responsible by Design Entity Resolution', 'Beautiful, beauti--FUL SOUP!\' \'Chorus again!\' cried the Gryphon. Alice did not look at it!\' This speech caused a remarkable sensation among the branches, and every now and then sat upon it.) \'I\'m.', '150000', '2020-11-19', '2024-02-02', 'GK', 46, 16, 46);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (47, 'Lifting Algorithms for Evolutionary Dynamics in Networks (LIFT)', 'And she thought at first she thought it over here,\' said the March Hare interrupted, yawning. \'I\'m getting tired of this. I vote the young lady to see if he wasn\'t one?\' Alice asked. \'We called him.', '700772.84', '2022-01-14', '2024-01-23', 'SteKo', 47, 17, 47);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (48, 'Censorship in Cinema and Visual Arts', 'Gryphon, the squeaking of the tea--\' \'The twinkling of the other players, and shouting \'Off with his head!\' or \'Off with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'And where HAVE my.', '420118.67', '2019-03-04', '2022-12-24', 'LeBa', 48, 18, 48);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (49, 'Corruption and state-corporate crime', 'Alice remarked. \'Right, as usual,\' said the Caterpillar; and it sat for a long time together.\' \'Which is just the case with my wife; And the moral of that dark hall, and wander about among those.', '420893.38', '2021-08-03', '2023-05-23', 'St.M', 49, 19, 49);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (50, 'Interactions of Veterinary antibiotics with soil microorganisms', 'Who for such dainties would not open any of them. However, on the floor, and a scroll of parchment in the air. She did not like to try the experiment?\' \'HE might bite,\' Alice cautiously replied:.', '100056.52', '2022-03-27', '2024-08-22', 'MuPu', 50, 20, 50);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (51, 'The Perils of Prediction in the Physical Science', 'Gryphon, before Alice could see, as well say,\' added the Gryphon; and then they both bowed low, and their curls got entangled together. Alice laughed so much into the court, \'Bring me the truth: did.', '866465.86', '2021-03-16', '2023-07-18', 'AaS', 1, 21, 51);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (52, 'Aegean Islands: Palaeoenvironment and Early Human Settlement', 'Bill\'s got to grow to my jaw, Has lasted the rest of it in a game of croquet she was dozing off, and found quite a long argument with the Lory, with a growl, And concluded the banquet--] \'What IS a.', '100999.99', '2021-12-19', '2023-10-06', 'AaS', 2, 22, 52);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (53, 'Assistance for students in Singing and Music Aesthetics', 'Let me see--how IS it to annoy, Because he knows it teases.\' CHORUS. (In which the words \'DRINK ME,\' but nevertheless she uncorked it and put it in asking riddles that have no answers.\' \'If you.', '208999.99', '2021-10-20', '2023-09-30', 'AaS', 3, 23, 53);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (54, 'Sourcebook of Byzantine Philosophy (SBPh)', 'Alice: \'allow me to introduce it.\' \'I don\'t even know what they\'re like.\' \'I believe so,\' Alice replied very readily: \'but that\'s because it stays the same as the doubled-up soldiers were silent,.', '465349.92', '2021-12-08', '2023-11-15', 'AaS', 4, 24, 54);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (55, 'Batteryless, Ambiently-Powered Internet of Things', 'Said his father; \'don\'t give yourself airs! Do you think I may as well say this), \'to go on with the other side will make you grow taller, and the happy summer days. THE.', '302999.99', '2021-08-01', '2023-06-12', 'RyanG', 5, 25, 55);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (56, 'Development of tissue-engineered vascularized bone grafts', 'Beautiful, beauti--FUL SOUP!\' \'Chorus again!\' cried the Gryphon. Alice did not look at it!\' This speech caused a remarkable sensation among the branches, and every now and then sat upon it.) \'I\'m.', '230999.99', '2021-11-19', '2025-11-02', 'AaS', 6, 26, 56);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (57, 'Innovative Catalyst Design via 3D Printing', 'And she thought at first she thought it over here,\' said the March Hare interrupted, yawning. \'I\'m getting tired of this. I vote the young lady to see if he wasn\'t one?\' Alice asked. \'We called him.', '700772.84', '2021-11-14', '2023-01-23', 'RyanG', 7, 27, 57);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (58, 'Electrochemical Analysis for the action of Lytic Polysaccharide Monooxygenases', 'Gryphon, the squeaking of the tea--\' \'The twinkling of the other players, and shouting \'Off with his head!\' or \'Off with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'And where HAVE my.', '420118.67', '2021-03-04', '2023-10-24', 'AaS', 8, 28, 58);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (59, 'Advanced photocatalytic Slow Photon nanostructures', 'Alice remarked. \'Right, as usual,\' said the Caterpillar; and it sat for a long time together.\' \'Which is just the case with my wife; And the moral of that dark hall, and wander about among those.', '420893.38', '2021-08-03', '2023-05-23', 'AaS', 9, 29, 59);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (60, 'Scaling stochastic dynamics', 'Who for such dainties would not open any of them. However, on the floor, and a scroll of parchment in the air. She did not like to try the experiment?\' \'HE might bite,\' Alice cautiously replied:.', '100056.52', '2021-08-27', '2023-08-22', 'AaS', 10, 30, 60);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (61, 'Finiteness Conditions in Homological Algebra', 'Gryphon, before Alice could see, as well say,\' added the Gryphon; and then they both bowed low, and their curls got entangled together. Alice laughed so much into the court, \'Bring me the truth: did.', '864965.86', '2021-03-16', '2023-07-18', 'AaS', 11, 1, 61);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (62, 'Dataflow optimization revisited', 'Bill\'s got to grow to my jaw, Has lasted the rest of it in a game of croquet she was dozing off, and found quite a long argument with the Lory, with a growl, And concluded the banquet--] \'What IS a.', '156999.00', '2021-12-19', '2023-01-05', 'RyanG', 12, 2, 62);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (63, 'A Toolkit for the Analysis and Synthesis of Soundscapes', 'Let me see--how IS it to annoy, Because he knows it teases.\' CHORUS. (In which the words \'DRINK ME,\' but nevertheless she uncorked it and put it in asking riddles that have no answers.\' \'If you.', '304999.99', '2021-10-20', '2023-09-30', 'RyanG', 13, 3, 63);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (64, 'Advanced Multi-Label Learning Techniques', 'Alice: \'allow me to introduce it.\' \'I don\'t even know what they\'re like.\' \'I believe so,\' Alice replied very readily: \'but that\'s because it stays the same as the doubled-up soldiers were silent,.', '203349.92', '2021-12-08', '2023-11-15', 'RyanG', 14, 4, 64);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (65, 'Inflationary models in the lhc and planck era', 'Said his father; \'don\'t give yourself airs! Do you think I may as well say this), \'to go on with the other side will make you grow taller, and the happy summer days. THE.', '100999.99', '2021-08-01', '2023-02-12', 'RyanG', 15, 5, 65);



/* The new projects i added*/
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (66, 'Archaeological and geophysical research in the coast of Samothrace', 'I\'ve been changed for Mabel! I\'ll try and repeat something now. Tell her to begin.\' He looked at them with the glass table and the party went back to the jury. They were indeed a queer-looking party.', '550000', '2021-03-26', '2023-09-10', 'AaS', 16, 6, 66);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (67, 'Linguistic  strategies for intervention in language disorders', 'King replied. Here the Queen put on one side, to look about her repeating \'YOU ARE OLD, FATHER WILLIAM,\' to the part about her other little children, and make out who was sitting next to no toys to.', '432000', '2022-08-01', '2024-03-22', 'AaS', 17, 7, 67);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (68, 'Genetic research & digital visualization in the performing arts', 'Off--\' \'Nonsense!\' said Alice, \'a great girl like you,\' (she might well say that \"I see what was the fan and gloves. \'How queer it seems,\' Alice said to herself how this same little sister of hers.', '990000', '2022-08-20', '2024-05-19', 'AaS', 18, 8, 68);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (69, 'Mapping patterns, impacts and threats to functional diversity', 'Gryphon went on, \'you throw the--\' \'The lobsters!\' shouted the Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice desperately: \'he\'s perfectly idiotic!\' And she tried to.', '800000', '2022-09-29', '2024-12-09', 'AaS', 19, 9, 69);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (70, 'Design of artificial wetlands for the treatment of gray water in urban areas of the Mediterranean', 'Alice did not like to drop the jar for fear of their hearing her; and the King had said that day. \'That PROVES his guilt,\' said the Caterpillar took the hookah into its mouth and began an account of.', '700000', '2022-11-13', '2024-05-02', 'AaS', 20, 10, 70);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (71, 'Human Resources Management in Small and Medium Enterprises', 'Queen. An invitation from the trees had a head could be beheaded, and that he shook his grey locks, \'I kept all my life!\' Just as she picked up a little now and then; such as, \'Sure, I don\'t think,\'.', '530299.97', '2022-08-31', '2023-10-26', 'AaS', 21, 11, 71);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (72, 'Exploring the quality characteristics of profits', 'Duchess\'s knee, while plates and dishes crashed around it--once more the pig-baby was sneezing on the bank--the birds with draggled feathers, the animals with their heads down and looked at Alice..', '643777.99', '2022-08-09', '2023-06-07', 'AaS', 22, 12, 72);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (73, 'Configuring the environment and nutrition', 'Hatter went on, \'What HAVE you been doing here?\' \'May it please your Majesty!\' the soldiers did. After these came the royal children; there were three little sisters--they were learning to draw, you.', '345000', '2022-12-30', '2024-11-20', 'AaS', 23, 13, 73);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (74, 'Alt-Right Social Networks: Investigating Political & Cultural Activism', 'Footman remarked, \'till tomorrow--\' At this moment the door of which was lit up by two guinea-pigs, who were all crowded together at one corner of it: for she was quite pale (with passion, Alice.', '431000', '2022-01-18', '2024-12-25', 'AaS', 24, 14, 74);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (75, 'Populist Constitutionalism', 'As they walked off together. Alice was not quite sure whether it was indeed: she was dozing off, and she grew no larger: still it was looking at them with one finger, as he said in a tone of the.', '100000', '2022-09-12', '2023-08-19', 'AaS', 25, 15, 75);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (76, 'Biological Metaphysics: Understanding Development Mechanisms', 'Queen put on his spectacles and looked along the passage into the garden with one finger pressed upon its nose. The Dormouse again took a great deal to ME,\' said Alice very meekly: \'I\'m growing.\'.', '160000', '2022-04-21', '2024-08-26', 'AaS', 26, 16, 76);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (77, 'Transitions, Immigration and Politics: Understanding Youth in Crisis', 'The jury all brightened up again.) \'Please your Majesty,\' he began, \'for bringing these in: but I shall have somebody to talk nonsense. The Queen\'s Croquet-Ground A large rose-tree stood near the.', '820000', '2021-04-19', '2023-07-24', 'RyanG', 27, 17, 77);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (78, 'Species on the brink of extinction', 'Alice could not think of nothing better to say a word, but slowly followed her back to the seaside once in the sea, though you mayn\'t believe it--\' \'I never thought about it,\' added the Queen..', '653777', '2021-01-06', '2022-11-22', 'RyanG', 28, 18, 78);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (79, 'Consumerism in a time of economic crisis', 'Queen, pointing to the baby, and not to her, And mentioned me to sell you a couple?\' \'You are old,\' said the Lory, as soon as there was no one else seemed inclined to say it over) \'--yes, that\'s.', '450000', '2021-02-17', '2023-01-02', 'RyanG', 29, 19, 79);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (80, 'Processors based on Optical Artificial Neurons', 'Alice to herself. \'I dare say there may be ONE.\' \'One, indeed!\' said the Rabbit say to itself, half to Alice. \'What IS the fun?\' said Alice. \'Oh, don\'t bother ME,\' said the Mock Turtle went on.', '200187.25', '2021-05-28', '2022-11-02', 'RyanG', 30, 20, 80);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (81, 'Assigning Meaning to the Actions of Other Subjects: Neural Correlates', 'Gryphon, before Alice could see, as well say,\' added the Gryphon; and then they both bowed low, and their curls got entangled together. Alice laughed so much into the court, \'Bring me the truth: did.', '86465.86', '2022-03-16', '2023-07-18', 'RyanG', 31, 21, 81);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (82, 'Modeling of Electromagnetic Emissions of Space Equipment', 'Bill\'s got to grow to my jaw, Has lasted the rest of it in a game of croquet she was dozing off, and found quite a long argument with the Lory, with a growl, And concluded the banquet--] \'What IS a.', '560000.99', '2022-12-19', '2023-10-06', 'RyanG', 32, 22, 82);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (83, 'Sociology of Foreign Direct Investment in Greece', 'Let me see--how IS it to annoy, Because he knows it teases.\' CHORUS. (In which the words \'DRINK ME,\' but nevertheless she uncorked it and put it in asking riddles that have no answers.\' \'If you.', '533356.99', '2012-12-20', '2024-09-30', 'RyanG', 33, 23, 83);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (84, 'Quantum Integrated Photon Circuits', 'Alice: \'allow me to introduce it.\' \'I don\'t even know what they\'re like.\' \'I believe so,\' Alice replied very readily: \'but that\'s because it stays the same as the doubled-up soldiers were silent,.', '463049.92', '2022-02-08', '2023-11-15', 'RyanG', 34, 24, 84);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (85, 'Inclined Cosmology', 'Said his father; \'don\'t give yourself airs! Do you think I may as well say this), \'to go on with the other side will make you grow taller, and the happy summer days. THE.', '560000', '2022-08-01', '2023-06-12', 'RyanG', 35, 25, 85);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (86, 'Responsible by Design Entity Resolution', 'Beautiful, beauti--FUL SOUP!\' \'Chorus again!\' cried the Gryphon. Alice did not look at it!\' This speech caused a remarkable sensation among the branches, and every now and then sat upon it.) \'I\'m.', '150000', '2022-11-19', '2024-02-02', 'RyanG', 36, 26, 86);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (87, 'Lifting Algorithms for Evolutionary Dynamics in Networks (LIFT)', 'And she thought at first she thought it over here,\' said the March Hare interrupted, yawning. \'I\'m getting tired of this. I vote the young lady to see if he wasn\'t one?\' Alice asked. \'We called him.', '700772.84', '2022-01-14', '2024-01-23', 'RyanG', 37, 27, 87);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (88, 'Censorship in Cinema and Visual Arts', 'Gryphon, the squeaking of the tea--\' \'The twinkling of the other players, and shouting \'Off with his head!\' or \'Off with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'And where HAVE my.', '420118.67', '2022-03-04', '2023-12-24', 'RyanG', 38, 28, 88);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (89, 'Corruption and state-corporate crime', 'Alice remarked. \'Right, as usual,\' said the Caterpillar; and it sat for a long time together.\' \'Which is just the case with my wife; And the moral of that dark hall, and wander about among those.', '420893.38', '2022-08-03', '2023-05-23', 'RyanG', 39, 29, 89);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (90, 'Interactions of Veterinary antibiotics with soil microorganisms', 'Who for such dainties would not open any of them. However, on the floor, and a scroll of parchment in the air. She did not like to try the experiment?\' \'HE might bite,\' Alice cautiously replied:.', '100056.52', '2022-03-27', '2024-08-22', 'RyanG', 40, 30, 90);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (91, 'The Perils of Prediction in the Physical Science', 'Gryphon, before Alice could see, as well say,\' added the Gryphon; and then they both bowed low, and their curls got entangled together. Alice laughed so much into the court, \'Bring me the truth: did.', '866465.86', '2022-03-16', '2023-07-18', 'RyanG', 41, 1, 91);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (92, 'Aegean Islands: Palaeoenvironment and Early Human Settlement', 'Bill\'s got to grow to my jaw, Has lasted the rest of it in a game of croquet she was dozing off, and found quite a long argument with the Lory, with a growl, And concluded the banquet--] \'What IS a.', '100999.99', '2022-12-19', '2024-10-06', 'RyanG', 42, 2, 92);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (93, 'Assistance for students in Singing and Music Aesthetics', 'Let me see--how IS it to annoy, Because he knows it teases.\' CHORUS. (In which the words \'DRINK ME,\' but nevertheless she uncorked it and put it in asking riddles that have no answers.\' \'If you.', '208999.99', '2022-10-20', '2023-09-30', 'RyanG', 43, 3, 93);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (94, 'Sourcebook of Byzantine Philosophy (SBPh)', 'Alice: \'allow me to introduce it.\' \'I don\'t even know what they\'re like.\' \'I believe so,\' Alice replied very readily: \'but that\'s because it stays the same as the doubled-up soldiers were silent,.', '465349.92', '2022-12-08', '2024-11-15', 'RyanG', 44, 4, 94);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (95, 'Batteryless, Ambiently-Powered Internet of Things', 'Said his father; \'don\'t give yourself airs! Do you think I may as well say this), \'to go on with the other side will make you grow taller, and the happy summer days. THE.', '302999.99', '2022-08-01', '2024-06-12', 'RyanG', 45, 5, 95);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (96, 'Development of tissue-engineered vascularized bone grafts', 'Beautiful, beauti--FUL SOUP!\' \'Chorus again!\' cried the Gryphon. Alice did not look at it!\' This speech caused a remarkable sensation among the branches, and every now and then sat upon it.) \'I\'m.', '230999.99', '2022-11-19', '2024-11-02', 'RyanG', 46, 6, 96);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (97, 'Innovative Catalyst Design via 3D Printing', 'And she thought at first she thought it over here,\' said the March Hare interrupted, yawning. \'I\'m getting tired of this. I vote the young lady to see if he wasn\'t one?\' Alice asked. \'We called him.', '700772.84', '2019-11-14', '2022-01-23', 'RyanG', 47, 7, 97);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (98, 'Electrochemical Analysis for the action of Lytic Polysaccharide Monooxygenases', 'Gryphon, the squeaking of the tea--\' \'The twinkling of the other players, and shouting \'Off with his head!\' or \'Off with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'And where HAVE my.', '420118.67', '2022-03-04', '2023-10-24', 'AaS', 48, 8, 98);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (99, 'Advanced photocatalytic Slow Photon nanostructures', 'Alice remarked. \'Right, as usual,\' said the Caterpillar; and it sat for a long time together.\' \'Which is just the case with my wife; And the moral of that dark hall, and wander about among those.', '420893.38', '2022-08-03', '2024-05-23', 'AaS', 49, 9, 99);
INSERT INTO `project` (`project_id`, `title`, `summary`, `funding`, `start_date`, `end_date`, `abbreviation`, `executive_id`, `program_id`, `scientific_inspector_id`)
VALUES (100, 'Scaling stochastic dynamics', 'Who for such dainties would not open any of them. However, on the floor, and a scroll of parchment in the air. She did not like to try the experiment?\' \'HE might bite,\' Alice cautiously replied:.', '100056.52', '2022-08-27', '2024-08-22', 'AaS', 50, 10, 100);
