/* {Fields: Physics, Computer Science, Engineering Sciences, Mathematics, Environment, Chemistry, Medicine, Art, Sociology, Economics }
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (1, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (2, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (3, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (3, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (4, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (4, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (5, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (5, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (6, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (6, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (7, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (7, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (8, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (8, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (9, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (10, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (10, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (11, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (11, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (12, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (13, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (14, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (15, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (16, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (16, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (17, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (17, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (18, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (18, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (19, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (20, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (21, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (21, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (22, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (22, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (23, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (24, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (25, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (26, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (27, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (28, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (29, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (30, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (30, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (31, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (32, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (33, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (33, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (34, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (35, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (36, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (37, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (38, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (39, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (39, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (40, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (40, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (41, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (42, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (42, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (43, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (44, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (44, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (45, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (45, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (46, 'Management');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (47, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (47, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (48, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (49, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (50, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (50, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (51, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (52, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (52, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (53, 'Art');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (53, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (54, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (55, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (55, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (56, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (56, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (57, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (57, 'Art');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (58, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (58, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (59, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (60, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (61, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (61, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (62, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (63, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (63, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (64, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (65, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (66, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (66, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (67, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (68, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (68, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (69, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (69, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (70, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (71, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (72, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (73, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (73, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (74, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (75, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (76, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (76, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (77, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (77, 'Engineering Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (78, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (79, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (79, 'Engineering Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (80, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (80, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (81, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (82, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (83, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (83, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (84, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (84, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (85, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (86, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (86, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (87, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (87, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (88, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (89, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (90, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (91, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (91, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (92, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (93, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (93, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (94, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (94, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (95, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (95, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (96, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (97, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (97, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (98, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (98, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (99, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (99, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (100, 'Computer Science');
