
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (1, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (2, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (3, 'Technology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (3, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (4, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (4, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (5, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (5, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (6, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (6, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (7, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (7, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (8, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (8, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (9, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (10, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (10, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (11, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (11, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (12, 'Linguistics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (13, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (14, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (15, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (16, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (16, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (17, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (17, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (18, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (18, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (19, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (20, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (21, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (21, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (22, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (22, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (23, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (24, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (25, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (26, 'Archaeology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (26, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (27, 'Linguistics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (28, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (29, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (30, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (30, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (31, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (32, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (33, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (33, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (34, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (35, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (36, 'Biology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (37, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (38, 'Environment');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (39, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (39, 'Economics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (40, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (40, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (41, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (42, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (42, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (43, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (44, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (44, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (45, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (45, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (46, 'Management');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (47, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (47, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (48, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (49, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (50, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (50, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (51, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (52, 'Sociology');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (52, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (53, 'Art');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (53, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (54, 'History');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (55, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (55, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (56, 'Engineering Sciences');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (56, 'Medicine');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (57, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (57, 'Art');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (58, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (58, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (59, 'Chemistry');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (60, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (61, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (61, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (62, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (63, 'Mathematics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (63, 'Physics');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (64, 'Computer Science');
INSERT INTO `scientific_field` (`project_id`, `scientific_field_name`) VALUES (65, 'Physics');
